services:
  backend:
    ports:
      - "8000:8000"
    command:
      - uvicorn
      - --reload
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - "app.main:app"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - .venv
            - .mypy_cache
            - __pycache__
